### ISSUE TITLE
Switcher not working properly

### ISSUE THREAD

**Issue by ScArWlvrne** [FanyaOff/Low-Durability-Switcher#1]
I'm unsure if there are limitations to the mod based on world type or tool type, or if it's because of some conflicting mod I have or whatever (maybe it's the default toggle button conflicting with my perspective toggle key?) but for whatever reason, when testing the mod on a creative world with a golden shovel (and later an iron one) switching was not working and the tools would just break. Mod folder is attached (in two separate files because it's slightly too large) for debugging/testing purposes.
[Mods Pt1.zip](https://github.com/FanyaOff/Low-Durability-Switcher/files/12289261/Mods.Pt1.zip)
[Mods Pt2.zip](https://github.com/FanyaOff/Low-Durability-Switcher/files/12289262/Mods.Pt2.zip)

**Comment by FanyaOff** [comment]
Hello, I found an error in your mod folder: cloth-config was for the forge version, but the fabric version was needed. Make sure that you have enabled the mod, a pop-up message will tell you about it
![javaw_h303Y5HCDC](https://github.com/FanyaOff/Low-Durability-Switcher/assets/73064979/de40def4-38db-467c-ade7-5ae6761a419e)
![javaw_CN8QavA6mx](https://github.com/FanyaOff/Low-Durability-Switcher/assets/73064979/27462cd5-42f1-4479-afa6-cf62c0992387)
![javaw_h303Y5HCDC](https://github.com/FanyaOff/Low-Durability-Switcher/assets/73064979/3df4d36b-b725-4e8e-8c27-dac5888837cd)
