### ISSUE TITLE
Does this mod Also unequipped armor whenever it becomes low on durability???

### ISSUE THREAD

**Issue by HatelessHeart** [FanyaOff/Low-Durability-Switcher#6]
Does this mod Also unequipped armor whenever it becomes low on durability??? This would Be an excellent feature if it doesn't

**Comment by FanyaOff** [comment]
Nice idea! I'll do it later, ty

**Comment by HatelessHeart** [comment]
> Nice idea! I'll do it later, ty

Is this still happening?

**Comment by FanyaOff** [comment]
> > Nice idea! I'll do it later, ty
> 
> Is this still happening?

I did sound alert if durability is low, cuz i have some problems with auto armor switching

**Comment by HatelessHeart** [comment]
Oh, OK so for now when armor is low instead of unequipped, it will simply give you a sound alert.. that's a pretty good improvision

**Comment by HatelessHeart** [comment]
> > > Nice idea! I'll do it later, ty
> > 
> > Is this still happening?
> 
> I did sound alert if durability is low, cuz i have some problems with auto armor switching

And you are still working on uploading the mod too?

**Comment by FanyaOff** [comment]
> Oh, OK so for now when armor is low instead of unequipped, it will simply give you a sound alert.. that's a pretty good improvision

oh i idk about this bug, i'll fix it
